import copy
import torch
import torch.nn as nn
import torch.nn.functional as f
import numpy as np 

import pickle
from collections import deque
import os 
from .decision_maker_base import DescisionMakerBase
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from lr_schedulers import Linear
from torch.optim.lr_scheduler import LambdaLR

# Define the DeepQNetwork class which inherits from nn.Module
class DeepQNetwork(nn.Module):
    """
    DeepQNetwork is a PyTorch module designed for the Deep Q-Learning algorithm with optional LSTM and dueling network architecture.
    This class combines fully-connected layers (and optionally LSTM) to estimate Q-values for a set of discrete actions, potentially splitting the network
    into separate streams for value and advantage if dueling is enabled.
    Args:
        state_dimensions (int): The dimensionality of the input state (excluding LSTM features).
        lstm_input_shape (int): The size of the input features that feed into the LSTM layers.
        lstm_output_shape (int): The number of output features generated by the LSTM each timestep.
        number_of_actions (int): The total number of discrete actions for which Q-values are estimated.
        hidden_layers (List[int]): A list of sizes for each fully-connected hidden layer after the state representation (and LSTM if used).
        lstm_layers (int): The number of stacked LSTM layers. A value of zero indicates no LSTM usage.
        dueling (bool): Indicates whether to use dueling architecture (separate streams for value and advantage).
        dropout_rate (float): The dropout probability applied after each hidden layer.
    Attributes:
        lstm_unit (nn.LSTM, optional): The recurrent module used if lstm_layers > 0. Maps sequential LSTM inputs to compressed features.
        sequential (nn.Sequential): Fully-connected layers that process the concatenated input (state + optional LSTM output).
        value_layer (nn.Linear, optional): The linear layer that estimates the baseline state-value in the dueling architecture.
        advantage_layer (nn.Linear, optional): The linear layer that estimates the advantage values for each action in the dueling architecture.
        output_layer (nn.Linear, optional): The single output layer for Q-values when the dueling architecture is disabled.
    Forward Pass:
        forward(state, lstm_input=None):
            1. Optionally processes the LSTM input if LSTM layers are used:
               - Initializes hidden/cell states to zeros.
               - Passes the sequence through the LSTM layers, then takes the last timestep output.
               - Concatenates the LSTM output with the raw state features.
            2. Passes the resulting features through the fully-connected (sequential) layers.
            3. If dueling is enabled, computes both value and advantage, then combines them to form final Q-values:
               Q(s,a) = Value(s) + Advantage(s,a) - mean(Advantage(s,a))
            4. Otherwise, outputs Q-values directly from the final layer.
    Returns:
        torch.Tensor: A tensor containing Q-values for each action. The shape is typically [batch_size, number_of_actions].
    """
    def __init__(self,
                 state_dimensions,
                 lstm_input_shape,
                 lstm_output_shape,
                 number_of_actions,
                 hidden_layers,
                 lstm_layers,
                 dueling,
                 dropout_rate):
        super(DeepQNetwork,self).__init__()

        # Initialize network parameters
        self.state_dimensions = state_dimensions
        self.lstm_input_shape = lstm_input_shape
        self.lstm_output_shape = lstm_output_shape
        self.number_of_actions = number_of_actions
        self.hidden_layers = hidden_layers
        self.lstm_layers = lstm_layers
        self.dueling = dueling
        
        # If LSTM layers are used, initialize LSTM unit
        if self.lstm_layers != 0:
            self.lstm_unit = nn.LSTM(input_size= lstm_input_shape, hidden_size=lstm_output_shape, num_layers=lstm_layers, batch_first=True)
            last_layer_size = state_dimensions + lstm_output_shape
        else:
            last_layer_size = state_dimensions
            
        # Create hidden layers
        layers = []
        for next_layer_size in hidden_layers:
            layers.append(nn.Linear(last_layer_size, next_layer_size))
            layers.append(nn.LeakyReLU())
            layers.append(nn.Dropout(dropout_rate))
            last_layer_size = next_layer_size

        self.sequential = nn.Sequential(*layers)
        
        # If dueling architecture is used, create separate value and advantage layers
        if self.dueling:
            self.value_layer = nn.Linear(last_layer_size, 1)
            self.advantage_layer = nn.Linear(last_layer_size, self.number_of_actions)
        else:
            self.output_layer = nn.Linear(last_layer_size, self.number_of_actions)
        
    def forward(self, state, lstm_input=None):
        # Forward pass through the network
        if self.lstm_layers != 0:
            batch_size = lstm_input.shape[0]
            h0 = torch.zeros(self.lstm_layers, batch_size, self.lstm_output_shape).to(lstm_input.device)
            c0 = torch.zeros(self.lstm_layers, batch_size, self.lstm_output_shape).to(lstm_input.device)
            lstm_output, _ = self.lstm_unit(lstm_input, [h0, c0])
            lstm_output = lstm_output[:, -1]
            network_input = torch.cat((state, lstm_output), dim=1)
        else:
            network_input = state
        sequential_output = self.sequential(network_input)
        
        # Compute Q-values using either dueling architecture or a single output layer
        if self.dueling:
            value = self.value_layer(sequential_output)
            advantage = self.advantage_layer(sequential_output)
            q_values = value + (advantage - torch.mean(advantage, dim=1, keepdim=True))
        else:
            q_values = self.output_layer(sequential_output)
            
        return q_values
    

# Define the Agent class which inherits from DescisionMakerBase
class Agent(DescisionMakerBase):
    """
    Agent class that uses Deep Q-Networks (DQN) with an LSTM-based architecture for decision-making.
    This class encapsulates all essential functionalities for training and deploying a DQN-based 
    agent with Long Short-Term Memory (LSTM) support, allowing it to effectively handle sequential 
    data within its observations.
    Attributes:
        id (int): Unique identifier for the agent instance.
        state_dimensions (int): Dimensionality of the environment's state.
        lstm_shape (int): Dimensionality of the LSTM's internal state representation.
        number_of_actions (int): Number of possible actions the agent can take.
        hidden_layers (list): List containing sizes of fully connected hidden layers in the DQN.
        lstm_layers (int): Number of layers in the LSTM stack.
        lstm_time_step (int): Number of consecutive history frames used to feed the LSTM.
        dropout_rate (float): Dropout probability to reduce overfitting within DQN and LSTM layers.
        device (torch.device): Device on which tensors and networks are allocated (CPU/GPU).
        epsilon (float): Exploration rate threshold; used for ε-greedy action selection.
        epsilon_decrement (float): Value by which epsilon is reduced after each learning step.
        epsilon_end (float): Minimum possible value of epsilon to ensure ongoing exploration.
        gamma (float): Discount factor for future rewards in Q-learning updates.
        learning_rate (float): Initial learning rate for the optimizer.
        scheduler_file (str): Path to a serialized function used as a learning rate schedule.
        loss_function (callable): Loss function constructor, e.g., torch.nn.MSELoss.
        optimizer (callable): Optimizer constructor, e.g., torch.optim.Adam or torch.optim.RMSprop.
        checkpoint_folder (str): Path or filename where the trained network weights are stored/loaded.
        save_model_frequency (int): Interval in steps at which to persist the trained model.
        update_weight_percentage (float): Fraction used to partially blend evaluation and target network weights.
        memory_size (int): Maximum size of the replay memory buffer.
        batch_size (int): Size of mini-batches sampled from the replay memory for learning.
        replace_target_iter (int): Interval specifying how often the target network gets updated.
    Key Methods:
        store_transitions(state, lstm_state, action, reward, new_state, new_lstm_state, done):
            Saves a single experience tuple in replay memory.
        reset_lstm_history():
            Clears the internal deque storing LSTM states.
        choose_action(observation, lstm_state):
            Selects an action using either the Q-network or random exploration, depending on ε.
        load_model(checkpoint_folder=None):
            Loads model weights from a specified checkpoint file.
        store_model(path=None):
            Persists the current evaluation network's weights to disk.
        learn():
            Performs one training step by sampling from memory, computing Q-updates, and 
            adjusting network parameters. Also handles target network updates, exploration 
            rate decay, and optimizer scheduling.
        get_epsilon():
            Retrieves the current exploration rate (ε) value, enabling external checks or logging.
    """
    def __init__(self, id, state_dimensions, lstm_shape, number_of_actions, hidden_layers, lstm_layers, lstm_time_step, dropout_rate, device, epsilon, epsilon_decrement, epsilon_end, gamma, learning_rate, scheduler_file, loss_function, optimizer, checkpoint_folder, save_model_frequency, update_weight_percentage, memory_size, batch_size, replace_target_iter, dueling=True):
        # Initialize agent parameters
        self.id = id
        self.state_dimensions = state_dimensions
        self.lstm_shape = lstm_shape
        self.number_of_actions = number_of_actions
        self.hidden_layers = hidden_layers
        self.lstm_layers = lstm_layers
        self.device = device
    
        self.lstm_time_step = lstm_time_step
        self.lstm_history = deque(maxlen=self.lstm_time_step)
        for _ in range(self.lstm_time_step):
            self.lstm_history.append(np.zeros([self.lstm_shape]))

        self.epsilon = epsilon
        self.epsilon_decrement = epsilon_decrement
        self.epsilon_end = epsilon_end
        self.gamma = gamma
        self.learning_rate = learning_rate
    
        self.checkpoint_folder = checkpoint_folder 
        self.save_model_frequency = save_model_frequency
        self.update_weight_percentage = update_weight_percentage
        
        # Initialize Q-networks
        self.Q_eval_network = DeepQNetwork(state_dimensions=state_dimensions, lstm_input_shape=lstm_shape, lstm_output_shape=lstm_shape, number_of_actions=number_of_actions, hidden_layers=hidden_layers, lstm_layers=lstm_layers, dropout_rate=dropout_rate, dueling=dueling).to(device)
        self.load_model()
        self.Q_target_network = copy.deepcopy(self.Q_eval_network).to(device)
        
        # Initialize loss function and optimizer
        self.loss_function = loss_function()
        self.optimizer = optimizer(self.Q_eval_network.parameters(), lr=learning_rate)
        
        # Load learning rate scheduler
        self.scheduler_file = scheduler_file
        with open(self.scheduler_file, 'rb') as f:
            self.schedueler_fun = pickle.load(f)
        self.scheduler = LambdaLR(self.optimizer, lr_lambda=self.schedueler_fun)
        
        # Initialize memory buffers
        self.memory_counter = 0
        self.learn_step_counter = 0
        self.replace_target_iter = replace_target_iter
        self.batch_size = batch_size
        self.memory_size = memory_size
        self.state_memory = np.zeros((self.memory_size, state_dimensions), dtype=np.float32)
        self.lstm_memory = np.zeros((self.memory_size, self.lstm_shape), dtype=np.float32)
        self.new_state_memory = np.zeros((self.memory_size, state_dimensions), dtype=np.float32)
        self.new_lstm_memory = np.zeros((self.memory_size, self.lstm_shape), dtype=np.float32)
        self.reward_memory = np.zeros(self.memory_size, dtype=np.float32)
        self.action_memory = np.zeros(self.memory_size, dtype=np.int64)
        self.terminal_memory = np.zeros(self.memory_size, dtype=bool)

    # Store transitions in memory
    def store_transitions(self, state, lstm_state, action, reward, new_state, new_lstm_state, done):
        index = self.memory_counter % self.memory_size
        self.state_memory[index] = state
        self.lstm_memory[index] = lstm_state
        self.action_memory[index] = action
        self.reward_memory[index] = reward
        self.new_state_memory[index] = new_state
        self.new_lstm_memory[index] = new_lstm_state
        self.terminal_memory[index] = done
        self.memory_counter += 1
        
    # Reset LSTM history
    def reset_lstm_history(self):
        self.lstm_history = deque(maxlen=self.lstm_time_step)
        for _ in range(self.lstm_time_step):
            self.lstm_history.append(np.zeros([self.lstm_shape]))
    
    # Choose an action based on the current state and LSTM state
    def choose_action(self, observation, lstm_state):  
        self.lstm_history.append(lstm_state)
        with torch.no_grad():
            if np.random.uniform() > self.epsilon:
                self.Q_eval_network.eval()
                observation_np = np.expand_dims(observation, axis=0)
                lstm_history_np = np.expand_dims(self.lstm_history, axis=0)

                observation = torch.tensor(observation_np, dtype=torch.float32).to(self.device)
                lstm_input = torch.tensor(lstm_history_np, dtype=torch.float32).to(self.device)
                action_values = self.Q_eval_network(observation, lstm_input).detach().cpu().numpy().flatten()
                action = np.argmax(action_values)
            else:
                action = np.random.choice(self.number_of_actions)
        return action
    
    # Load model weights from a checkpoint
    def load_model(self, checkpoint_folder=None):
        if not checkpoint_folder:
            checkpoint_folder = self.checkpoint_folder
        try:
            if os.path.isfile(checkpoint_folder):
                self.Q_eval_network = torch.load(checkpoint_folder, map_location=self.device)
                print('model weights loaded')
            else:
                print('weights folder not found')
        except Exception as e:
            print('An error occurred while loading the model weights:', str(e)) 
    
    # Store model weights to a checkpoint
    def store_model(self, path=None):
        if not path:
            path = self.checkpoint_folder
        torch.save(self.Q_eval_network, path)
        
    # Perform learning step
    def learn(self):
        def weighted_add_state_dicts():
            eval_state_dict = self.Q_eval_network.state_dict()
            target_state_dict = self.Q_target_network.state_dict()
            new_state_dict = {}
            for key in target_state_dict.keys():
                new_state_dict[key] = self.update_weight_percentage * eval_state_dict[key] + target_state_dict[key] * (1 - self.update_weight_percentage)
            return new_state_dict
        
        def get_lstm_sequence(index):
            start_index = max(0, index - self.lstm_time_step + 1)
            return torch.tensor(self.lstm_memory[start_index:index])

        if self.memory_counter <= self.batch_size + self.lstm_time_step:
            return 

        self.Q_eval_network.train()
        self.learn_step_counter += 1
        if self.learn_step_counter % self.replace_target_iter == 0:
            new_target_weights = weighted_add_state_dicts()
            self.Q_target_network.load_state_dict(new_target_weights)

        self.optimizer.zero_grad()

        max_memory = min(self.memory_counter, self.memory_size)
        batch_indices = np.random.choice(range(self.lstm_time_step, max_memory), self.batch_size, replace=False)

        state_batch = torch.tensor(self.state_memory[batch_indices]).to(self.device)
        lstm_sequence_batch = [get_lstm_sequence(index) for index in batch_indices]
        lstm_sequence_batch = torch.stack(lstm_sequence_batch).to(self.device)
        action_batch = torch.tensor(self.action_memory[batch_indices]).to(self.device)
        reward_batch = torch.tensor(self.reward_memory[batch_indices]).to(self.device)
        next_state_batch = torch.tensor(self.new_state_memory[batch_indices]).to(self.device)
        next_lstm_sequence_batch = [get_lstm_sequence(index + 1) for index in batch_indices]
        next_lstm_sequence_batch = torch.stack(next_lstm_sequence_batch).to(self.device)
        terminal_batch = torch.tensor(self.terminal_memory[batch_indices]).to(self.device)

        q_eval = self.Q_eval_network(state_batch, lstm_sequence_batch).gather(1, action_batch.unsqueeze(1)).squeeze(1)
        q_next_eval = self.Q_eval_network(next_state_batch, next_lstm_sequence_batch)
        next_actions = torch.argmax(q_next_eval, dim=1)
        q_next_target = self.Q_target_network(next_state_batch, next_lstm_sequence_batch)
        q_target_next = q_next_target.gather(1, next_actions.unsqueeze(1)).squeeze(1)
        
        mask = (terminal_batch == 0)
        q_target_next = q_target_next * mask
        q_target = reward_batch + self.gamma * q_target_next

        loss = self.loss_function(q_eval, q_target)
        loss.backward()
        self.optimizer.step()
        
        self.epsilon = max(self.epsilon - self.epsilon_decrement, self.epsilon_end)
        
        with open(self.scheduler_file, 'wb') as f:
            pickle.dump(self.schedueler_fun, f)

        if self.learn_step_counter % self.save_model_frequency == 0:
            self.store_model()
            
        self.scheduler.step()
    
    # Get the current value of epsilon
    def get_epsilon(self):
        return self.epsilon
